Fix mistakes

diff --git a/shaber b/shaber
--- a/shaber
+++ b/shaber
@@ -662,7 +662,7 @@ ipa_native_download_latest() {
 ipa_native_patch() {
   tool_mod_check_local "BSIPA"    || { log_error "BSIPA is not downloaded or enabled."; exit 1; }
   tool_mod_check_enabled "BSIPA"  || { log_error "BSIPA is not enabled."; exit 1; }
-  [ -d "$ipa_native_dir" ]        || { log_error "Native Linux IPA is not downloaded."; exit 1 }
+  [ -d "$ipa_native_dir" ]        || { log_error "Native Linux IPA is not downloaded."; exit 1; }
   [ -f "$bs_dir/../../compatdata/620980/pfx/user.reg" ] || { 
     log_error "Beat Saber Proton prefix not detected: please run the game once, and check that
 you have set the game's directory correctly."; exit 1
@@ -897,7 +897,7 @@ parse_helper_mod_remove() {
     then
       mod_remove_all
     else
-      tool_mod_check_dependency "$arg" && { log_error "Mod '$arg' is depended upon, and cannot be removed."; exit 1 }
+      tool_mod_check_dependency "$arg" && { log_error "Mod '$arg' is depended upon, and cannot be removed."; exit 1; }
       mod_remove "$arg"
     fi
   done
@@ -921,7 +921,7 @@ parse_helper_mod_list() {
 parse_helper_mod_settype() {
   [ $# -lt 2 ] && { log_error "Two or more arguments expected, but $# given."; exit 1; }
   mod_type="$1"; shift
-  [ "$mod_type" = "explicit" ] || [ "$mod_type" = "dependency" ] || { log_error "First argument must be either 'explicit' or 'dependency'."; exit 1 }
+  [ "$mod_type" = "explicit" ] || [ "$mod_type" = "dependency" ] || { log_error "First argument must be either 'explicit' or 'dependency'."; exit 1; }
   config_get
   self_check_dependencies
   for arg
